module.exports = {
  'at': require('./collection/at'),
  'countBy': require('./collection/countBy'),
  'each': require('./collection/each'),
  'eachRight': require('./collection/eachRight'),
  'every': require('./collection/every'),
  'filter': require('./collection/filter'),
  'find': require('./collection/find'),
  'findLast': require('./collection/findLast'),
  'forEach': require('./collection/forEach'),
  'forEachRight': require('./collection/forEachRight'),
  'groupBy': require('./collection/groupBy'),
  'includes': require('./collection/includes'),
  'invoke': require('./collection/invoke'),
  'keyBy': require('./collection/keyBy'),
  'map': require('./collection/map'),
  'partition': require('./collection/partition'),
  'reduce': require('./collection/reduce'),
  'reduceRight': require('./collection/reduceRight'),
  'reject': require('./collection/reject'),
  'sample': require('./collection/sample'),
  'sampleSize': require('./collection/sampleSize'),
  'shuffle': require('./collection/shuffle'),
  'size': require('./collection/size'),
  'some': require('./collection/some'),
  'sortBy': require('./collection/sortBy'),
  'sortByOrder': require('./collection/sortByOrder')
};
